name:                TechHUB-Haskell
version:             0.1.0.0
github:              "DavidHODs/TechHUB-Haskell"
license:             BSD3
author:              "David Oluwatobi"
maintainer:          "davidoluwatobi41@gmail.com"
copyright:           "2022 David Oluwatobi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DavidHODs/TechHUB-Haskell#readme>

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DataKinds
- TypeOperators
- FlexibleInstances
- InstanceSigs

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- servant
- servant-server
- wai
- warp
- postgresql-simple

library:
  source-dirs: src

executables:
  TechHUB-Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TechHUB-Haskell

tests:
  TechHUB-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TechHUB-Haskell
