BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE SCHEMA IF NOT EXISTS tech;

CREATE TABLE IF NOT EXISTS tech.users(
	id uuid NOT NULL DEFAULT gen_random_uuid () PRIMARY KEY,
	name VARCHAR (127) NOT NULL,
	email VARCHAR (127) NOT NULL UNIQUE,
	password VARCHAR (127) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS tech.tags(
	id uuid NOT NULL DEFAULT gen_random_uuid () PRIMARY KEY UNIQUE,
	name VARCHAR (127) NOT NULL
);

CREATE TABLE IF NOT EXISTS tech.posts (
	id uuid NOT NULL DEFAULT gen_random_uuid () PRIMARY KEY,
	body VARCHAR (1027) NOT NULL,
	shared_body VARCHAR (1027),
	image VARCHAR (127),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
	update_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
	shared_at TIMESTAMP WITH TIME ZONE,
	author uuid NOT NULL REFERENCES tech.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	shared_user uuid REFERENCES tech.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	likes uuid REFERENCES tech.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	Dislikes uuid REFERENCES tech.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	Tags uuid REFERENCES tech.tags (id) ON DELETE CASCADE ON UPDATE CASCADE
);

END;